PROGRAM_EXIT = 4
USER_ID = 1
DATABASES = {
    "USERS_DATABASE": "usersDatabase",
    "COMPUTERS_DATABASE": "computersDatabase",
}
DATABASE_EXIST = 1
KEY_EXIST = 2
KEY_DOES_NOT_EXIST = 3
DATABASE_DOES_NOT_EXIST = 4
